photocee/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_wtf.csrf import CsrfProtect
import flask_uploads
from flask_coverapi import CoverSessionManager

# Init app
app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)
migrate = Migrate(app, db)

session_manager = CoverSessionManager(app.config['COVER_APP'], app.config['COVER_SECRET'], flask_app=app)

photos_uploadset = flask_uploads.UploadSet('photos', flask_uploads.IMAGES)
flask_uploads.configure_uploads(app, (photos_uploadset,))

CsrfProtect(app)

from .planner import planner, models
from .wall_of_fame import wall_of_fame, models
from .contests import contests, models

app.register_blueprint(planner)
app.register_blueprint(wall_of_fame)
app.register_blueprint(contests)

from . import views, utils

photocee/contests/__init__.py
from flask import Blueprint

contests = Blueprint('contests', __name__, url_prefix='/contests')

from . import views, utils

photocee/contests/views.py
from PIL import Image

from flask import render_template, url_for, redirect, request
from flask_coverapi import admin_required, login_required, current_user

from photocee import db, photos_uploadset
from photocee.caching import serve_cached_image

from . import contests
from .models import Poll, PollOption, PollVote, PollVoteRegistered
from .forms import PollForm, PollOptionForm, PollVoteForm
from .utils import randomize_for_user, get_poll_option_index, get_previous_poll_option_id, get_next_poll_option_id


@contests.route('/', methods=['GET'])
def main():
    view = request.args.get('view', 'default')

    if not current_user.is_anonymous:
        cover_id = current_user.get_id()
    else:
        cover_id = 0
    votes = PollVoteRegistered.query.filter_by(cover_id=cover_id).all()

    if view == 'archived':
        polls = Poll.query.order_by(Poll.deadline.desc()).all()
    else:
        polls = Poll.query.filter_by(archived=False).order_by(Poll.deadline.desc()).all()

    return render_template('contests/main.html', view=view, polls=polls, votes=[v.poll_id for v in votes])


@contests.route('/polls/add', methods=['GET','POST'])
@admin_required
def polls_add():
    form = PollForm()
    if form.validate_on_submit():
        poll = Poll(
            name=form.name.data,
            description=form.description.data,
            deadline=form.deadline.data,
            archived=form.archived.data,
        )
        db.session.add(poll)
        db.session.commit()
        return redirect(url_for('contests.polls_view', poll_id=poll.id))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Add poll',
        'cancel_url': url_for('contests.main')
    })


@contests.route('/polls/<int:poll_id>', methods=['GET'])
@admin_required
def polls_view(poll_id):
    poll = Poll.query.get_or_404(poll_id)
    results = []
    for idx, option in enumerate(poll.options):
        votes = option.votes.all()
        results.append({
            'option_id': option.id,
            'display': 'Photo {}'.format(idx+1),
            'votes': len(votes)
            })
    number_votes = sum([r['votes'] for r in results])
    form = PollOptionForm()
    return render_template('contests/poll.html', 
        poll=poll, 
        results=results, 
        number_votes=number_votes,
        form=form
        )


@contests.route('/polls/<int:poll_id>/vote', methods=['GET', 'POST'])
@login_required
def polls_vote(poll_id):
    poll = Poll.query.get_or_404(poll_id)
    form = PollVoteForm()
    form.choice.choices = [(o.id, "Photo {}".format(idx+1)) for idx, o in enumerate(randomize_for_user(poll.options))]
    if form.validate_on_submit():
        vote = PollVote(
            position=1,
            poll_option_id=form.choice.data,
            )
        registered = PollVoteRegistered(
            cover_id=current_user.get_id(),
            poll_id=poll.id
            )
        db.session.add(vote)
        db.session.add(registered)
        db.session.commit()
        return redirect(url_for('contests.main'))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Choose your favourite photo!',
        'cancel_url': url_for('contests.main')
    })


@contests.route('/polls/<int:poll_id>/edit', methods=['GET','POST'])
@admin_required
def polls_edit(poll_id):
    poll = Poll.query.get_or_404(poll_id)
    form = PollForm(request.form, poll)
    if form.validate_on_submit():
        form.populate_obj(poll)
        db.session.commit()
        return redirect(url_for('contests.polls_view', poll_id=poll.id))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Edit poll',
        'cancel_url': url_for('contests.polls_view', poll_id=poll.id)
    })


@contests.route('/polls/<int:poll_id>/options/add', methods=['GET', 'POST'])
@admin_required
def poll_options_add(poll_id):
    poll = Poll.query.get_or_404(poll_id)
    form = PollOptionForm()
    if form.validate_on_submit():
        filename = photos_uploadset.save(form.photo.data)
        with Image.open(photos_uploadset.path(filename)) as im:
            width, height = im.size
        poll_option = PollOption(
            description=form.description.data,
            photo_name=filename,
            width=width,
            height=height,
            poll=poll
        )
        db.session.add(poll_option)
        db.session.commit()
        return redirect(url_for('contests.polls_view', poll_id=poll.id))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Add option to {}'.format(poll.name),
        'cancel_url': url_for('contests.polls_view', poll_id=poll.id),
        'form_kwargs': {'upload': True}
    })


@contests.route('/polls/options/<int:poll_option_id>', methods=['GET'])
def poll_options_view(poll_option_id):
    poll_option = PollOption.query.get_or_404(poll_option_id)
    return render_template(
        'contests/poll_option.html',
        poll_option=poll_option,
        current_index=get_poll_option_index(poll_option.poll.options, poll_option),
        previous_id=get_previous_poll_option_id(poll_option.poll.options, poll_option),
        next_id=get_next_poll_option_id(poll_option.poll.options, poll_option)
    )


@contests.route('/polls/options/<int:poll_option_id>/photo', methods=['GET'])
def poll_options_photo(poll_option_id):
    width = request.args.get('width', None)
    height = request.args.get('height', None)
    if width and width.strip():
        width = int(float(width))
    if height and height.strip():
        height = int(float(height))
    poll_option = PollOption.query.get_or_404(poll_option_id)
    return serve_cached_image('photos', poll_option.photo_name, width, height)


@contests.route('/polls/options/<int:poll_option_id>/delete', methods=['GET', 'POST'])
@admin_required
def poll_options_delete(poll_option_id):
    poll_option = PollOption.query.get_or_404(poll_option_id)
    if request.method == 'POST':
        db.session.delete(poll_option)
        db.session.commit()
        return redirect(url_for('contests.polls_view', poll_id=poll_option.poll_id))
    return render_template('contests/poll_option_delete_form.html', poll_option=poll_option, meta={
        'name': 'Delete photo',
        'cancel_url': url_for('contests.polls_view', poll_id=poll_option.poll_id)
    })

photocee/planner/__init__.py
from flask import Blueprint

planner = Blueprint('planner', __name__, url_prefix='/planner')

from . import views

photocee/planner/views.py
from __future__ import division

from flask import request, render_template, redirect, url_for, abort, flash, get_flashed_messages, current_app
from flask_coverapi import admin_required, current_user, CoverSession

from sqlalchemy.orm import Load
from sqlalchemy.sql import func

from urlparse import urlparse, urljoin
from datetime import datetime

import sqlalchemy_utils
import json

from photocee import db
from photocee.utils import redirect_or_next, url_for_or_next

from . import planner
from .models import Activity, Photographer, PHOTOGRAPHER_STATUS_OPTIONS
from .forms import ActivityForm, PhotographerForm


def _update_activities():
    activities = current_app.cover_session_manager.request_json({
            'method': 'agenda',
            'session_id': current_user.session_id
        })
    for activity in activities:
        if activity['replacement_for'] is not None:
            # Unapproved activity, skip.
            continue
        saved_activity = Activity.query.filter_by(cover_id=activity['id']).first()
        if not saved_activity:
            saved_activity = Activity(cover_id=int(activity['id']))
            db.session.add(saved_activity)
        saved_activity.name = activity['kop']
        saved_activity.date = datetime.strptime(activity['van'].split('+', 1)[0], '%Y-%m-%d %H:%M:%S')
        saved_activity.location = activity['locatie']
    db.session.commit()


def _apply_filters(query):
    filters = {}

    if request.args.get('archived') == 'None':
        archived = None
    else:
        archived = request.args.get('archived') == 'True'

    if archived is not None:
        query = query.filter(Activity.archived == archived)

    if request.args.get('published') and request.args.get('published') != 'None':
        filters['published'] = request.args.get('published') == 'True'
        query = query.filter(Activity.published == filters['published'])

    if request.args.get('status') or request.args.get('photographers'):
        photographers_query = db.session.query(Photographer.activity_id)

        if request.args.get('photographers'):
            filters['photographers'] = request.args.get('photographers')
            photographers = request.args.get('photographers').split(',')
            photographers_query = photographers_query.filter(Photographer.cover_id.in_(photographers))

        if request.args.get('status'):
            filters['status'] = request.args.getlist('status')
            photographers_query = photographers_query.filter(Photographer.status.in_(filters['status']))

        query = query.filter(Activity.id.in_(photographers_query.subquery()))

    if filters or request.args.get('archived'):
        filters['archived'] = archived

    return query, filters


@planner.route('/', methods=['GET'])
@admin_required
def main():
    _update_activities()
    
    my_activities_subq = Photographer.query.filter_by(cover_id=current_user.get_id()).subquery()
    activities_query = db.session.query(Activity, my_activities_subq.c.status.label('my_status')).outerjoin(my_activities_subq, Activity.id==my_activities_subq.c.activity_id)
    
    backlog = db.session.query(func.count(Activity.id))\
                .outerjoin(my_activities_subq, Activity.id==my_activities_subq.c.activity_id)\
                .filter(my_activities_subq.c.cover_id == current_user.get_id())\
                .filter(my_activities_subq.c.status == u'0')\
                .filter(Activity.archived==False)\
                .filter(Activity.date < datetime.now())\
                .scalar()

    #filters
    activities_query, filters = _apply_filters(activities_query)

    activities = activities_query.order_by(Activity.date.desc()).all()

    return render_template('planner/planner.html', 
                           activities=activities, 
                           status_options=dict(PHOTOGRAPHER_STATUS_OPTIONS),
                           status_options_json=json.dumps(dict(PHOTOGRAPHER_STATUS_OPTIONS)), 
                           filters=filters,
                           backlog=backlog)


@planner.route('/status', methods=['POST'])
@admin_required
def update_status():
    photographer = current_user
    for key, value in request.form.iteritems():
        fieldname = key.split('-', 1)
        if not fieldname[0] == 'status':
            continue

        activity_id = fieldname[-1]
        activity = Activity.query.get(activity_id)
        if activity:
            add_or_update_photographer(photographer, activity, value)
    db.session.commit()
    return redirect_or_next(url_for('planner.main'))


def add_or_update_photographer(photographer, activity, status):
    saved_photographer = Photographer.query.filter_by(activity_id=activity.id).filter_by(cover_id=photographer.get_id()).first()
    if not saved_photographer:
        saved_photographer = Photographer(activity_id=activity.id, cover_id=photographer.get_id(), name=photographer.full_name, status=status)
        db.session.add(saved_photographer)
    else:
        saved_photographer.status = status
    auto_archive(activity)


def auto_archive(activity):
    if not activity.published:
        return
    db.session.commit()
    if not Photographer.query.filter_by(activity_id=activity.id).filter(Photographer.status.in_([u'0', u'2', u'3'])).first():
        activity.archived = True
    else: 
        activity.archived = False


@planner.route('/activity/<int:activity_id>/status/add', methods=['GET', 'POST'])
@admin_required
def add_status_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    form = PhotographerForm()
    if form.validate_on_submit():
        response = current_app.cover_session_manager.request_json({
            'method': 'get_member',
            'session_id': current_user.session_id,
            'member_id': form.photographer_cover_id.data
        })
        if 'result' in response:
            photographer = CoverSession(current_user.api, current_user.session_id, response['result'])
        else:
            return "Invalid Cover Member ID", 400
        add_or_update_photographer(photographer, activity, form.status.data)
        db.session.commit()
        return redirect_or_next(url_for('planner.main'))
    return render_template('planner/photographer_form.html', form=form, activity=activity, meta={
        'name': 'Add photographer',
        'cancel_url': url_for_or_next('planner.main')
    })


@planner.route('/<int:activity_id>/archive', methods=['GET'])
@admin_required
def archive_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    activity.archived = request.args.get('archive') != 'False'
    db.session.commit()
    return redirect_or_next(url_for('planner.main'))


@planner.route('/<int:activity_id>/publish', methods=['GET'])
@admin_required
def publish_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    activity.published = request.args.get('publish') != 'False'
    auto_archive(activity)
    db.session.commit()
    return redirect_or_next(url_for('planner.main'))


@planner.route('/activity/add', methods=['GET', 'POST'])
@admin_required
def add_activity():
    """ Try to create a new activity. """
    form = ActivityForm()
    if form.validate_on_submit():
        activity = Activity(
            name=form.name.data, description=form.description.data, location=form.location.data, date=form.date.data, cover_id=form.cover_id.data)
        db.session.add(activity)
        db.session.commit()
        return redirect(url_for('planner.main'))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Add activity',
        'cancel_url': url_for('planner.main')
    })



@planner.route('/activity/<int:activity_id>', methods=['GET', 'POST'])
@admin_required
def edit_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    form = ActivityForm(request.form, activity)
    if form.validate_on_submit():
        form.populate_obj(activity)
        db.session.commit()
        return redirect_or_next(url_for('planner.main'))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Edit activity',
        'cancel_url': url_for_or_next('planner.main')
    })

photocee/views.py
import requests

from flask import render_template, request, jsonify
from flask_coverapi import admin_required, current_user, CoverSession

from . import app

@app.route('/', methods=['GET'])
def view_home():
    return render_template('index.html')


@app.route('/almanakproxy', methods=['GET'])
@admin_required
def almanakproxy():
    cover_cookie_name = app.config.get('COVER_COOKIE_NAME', 'cover_session_id')
    almanak_url = app.config.get('COVER_ALMANAK_URL', 'https://www.svcover.nl/almanak.php')
    params = dict(request.args)
    if request.cookies.get(cover_cookie_name):
        params['session_id'] = request.cookies.get(cover_cookie_name)
    response = requests.get(almanak_url, params=params, headers={'accept': 'application/json, text/javascript'})
    response.raise_for_status()
    return response.text


@app.route('/almanakreverse', methods=['GET'])
@admin_required
def almanakreverse():
    query = request.args.get('search', '').split(',')
    def generate(data):
        for member_id in data:
            print member_id
            response = app.cover_session_manager.request_json({
                'method': 'get_member',
                'session_id': current_user.session_id,
                'member_id': member_id
            })

            if not 'result' in response:
                continue

            photographer = CoverSession(current_user.api, current_user.session_id, response['result'])
            yield {
                'id': photographer.get_id(),
                'name': photographer.full_name,
                'first_name': photographer.user['voornaam']
            }
    return jsonify(list(generate(query)))

photocee/wall_of_fame/__init__.py
from flask import Blueprint

wall_of_fame = Blueprint('wall_of_fame', __name__, url_prefix='/wall-of-fame')

from . import views

photocee/templates/contests/main.html
{% extends "base.html" %}

{% block css %}
	{{ super() }}
	<link rel="stylesheet" href="{{ url_for('static', filename='css/gallery.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/contests.css') }}">
{% endblock %}

{% block page_title %}Contests{% endblock %}

{% block header %}
	{{ super() }}
	{% if current_cover_user.is_admin %}
	<div class="controls">
		<a href="{{url_for('contests.polls_add')}}" class="btn btn-default" data-popup="modal">Add contest</a>
		{% if view == 'archived' %}
			<a href="{{url_for('contests.main')}}" class="btn btn-default">Back</a>
		{% else %}
			<a href="{{url_for('contests.main', view='archived')}}" class="btn btn-default">View archive</a>
		{% endif %}
	</div>
	{% endif %}
{% endblock %}

{% block content %}
{% for poll in polls %}
	<div class="poll">
		<h2>{{ poll.name }}</h2>
		{% if poll.description %}
			<p>{{ poll.description }}</p>
		{% endif %}
		{% if poll.options %}
			<h3>Photo's</h3>
			<div class="gallery">
				{% for option in poll.options|randomize_for_user %}
					<div class="photo">
						<img src="{{ url_for('contests.poll_options_photo', poll_option_id=option.id, width=800 * (option.width/option.height), height=800) }}" alt="Photo {{loop.index}}" width="{{ 400 * (option.width/option.height) }}" height="400">
						<div class="overlay">
			                <div class="title">
								Photo {{loop.index}}{% if option.description %}:
									{{option.description}}
								{% endif %}
							</div>
							<div class="controls">
								<a class="enlarge-button" href="{{ url_for('contests.poll_options_view', poll_option_id=option.id) }}" data-popup="modal"><i class="fa fa-expand" aria-hidden="true"></i></a>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
			<h3>Vote</h3>
			{% if poll.id in votes %}
				<p>You have already voted for this contest!</p>
			{% elif poll is expired %}
				<p>You cannot vote anymore, the voting deadline for this poll has passed :(</p>
			{% elif current_cover_user.is_anonymous %}
				<a href="{{login_url()}}">Login at Cover</a> to vote!
			{% else %}
				<form method="POST" action="{{ url_for('contests.polls_vote', poll_id=poll.id)}}" role="form" class="form">
				    <div style="display:none;"><input id="csrf_token" name="csrf_token" value="{{ csrf_token() }}" type="hidden"></div>
					<p>Which photo is your favourite?</p>
					{% for option in poll.options|randomize_for_user %}
						<div class="radio">
							<label>
								<input type="radio" name="choice" id="choice{{loop.index}}" value="{{ option.id }}">
								Photo {{loop.index}}
							</label>
						</div>
					{% endfor %}
					<div class="form-group">
						<button type="submit" class="btn btn-default">Vote!</button>
					</div>
				</form>
			{% endif %}
		{% endif %}
		<ul class="list-inline text-muted">
			<li>Voting deadline: {{poll.deadline.strftime('%d %b, %H:%M') }}</li>
			{% if current_cover_user.is_admin %}
				<li>&ndash;</li>
				<li><a 	href="{{url_for('contests.polls_view', poll_id=poll.id)}}">View contest</a></li>
			{% endif %}
		</ul>
	</div>
{% else %}
	No open contests :(
{% endfor %}
{% endblock %}

{% block scripts %}
	{{ super() }}
    <script src="{{ url_for('static', filename='js/jquery.row-grid.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('.gallery').rowGrid({
                itemSelector: '.photo',
                resize: true,
                minMargin: 5,
                maxMargin: 5
            });
        });
    </script>
	<script src="{{ url_for('static', filename='js/dialog.js') }}"></script>
    <script>
		$(document).on('ready dialog-content-loaded', function(e){
			var $dialog = $(e.target);
			$dialog.find('.pager a').data('popup', 'modal');
			$dialog.find('.pager a').on('click', function(e){
				loadDialog(e, this);
				$dialog.modal('hide');
			});
		});
    </script>
{% endblock %}

photocee/templates/contests/poll.html
{% extends "base.html" %}

{% from 'form_macros.html' import render_form %}

{% block css %}
	{{ super() }}
	<link rel="stylesheet" href="{{ url_for('static', filename='css/gallery.css') }}">
{% endblock %}

{% block page_title %}Poll: {{poll.name}}{% endblock %}

{% block content %}
<p>{{ poll.description }}</p>
<ul class="list-inline text-muted">
	<li>Deadline: {{poll.deadline.strftime('%d %b, %H:%M') }}</li>
    <li>&ndash;</li>
	<li>Archived: {{poll.archived }}</li>
    <li>&ndash;</li>
	<li><a 	href="{{url_for('contests.polls_edit', poll_id=poll.id)}}" data-popup="modal">Edit contest</a></li>
</ul>
<div class="poll-options">
	<h2>Photos</h2>
	<p>NB: To improve on the fairness of the vote, a random order is determined for every voter.</p>
	<div class="gallery">
		{% for option in poll.options %}
			<div class="photo">
				<img src="{{ url_for('contests.poll_options_photo', poll_option_id=option.id, width=800 * (option.width/option.height), height=800) }}" alt="Photo {{loop.index}}" width="{{ 400 * (option.width/option.height) }}" height="400">
				<div class="overlay">
	                <div class="title">
						Photo {{loop.index}}{% if option.description %}:
							{{option.description}}
						{% endif %}
					</div>
					<div class="controls">
						<a href="{{url_for('contests.poll_options_delete', poll_option_id=option.id)}}" data-popup="modal"><i class="fa fa-trash fa-fw" aria-hidden="true"></i></a>
						<a class="enlarge-button" href="{{ url_for('contests.poll_options_view', poll_option_id=option.id) }}" data-popup="modal"><i class="fa fa-expand" aria-hidden="true"></i></a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	<h3>Add photo</h3>
	{{ render_form(form, action_url=url_for('contests.poll_options_add', poll_id=poll.id), action_text='Add photo', class_="container-narrow", upload=True) }}
</div>
<div class="poll-results">
	<h2>Results</h2>
	{% if number_votes > 0 %}
		<ol>
		{% for result in results|sort(attribute='votes', reverse=True) %}
			<li>
				<a class="enlarge-button" href="{{ url_for('contests.poll_options_photo', poll_option_id=result.option_id, width=1800) }}" data-popup="image" title="{{result.display}}">{{result.display}}</a>
				with {{result.votes}}/{{number_votes}} votes
				({{(100*result.votes/number_votes)|round(2)}}%).
			</li>
		{% endfor %}
		</ol>
	{% else %}
		Nobody has voted for this poll yet :(
	{% endif %}
</div>
{% endblock %}

{% block scripts %}
	{{ super() }}
    <script src="{{ url_for('static', filename='js/jquery.row-grid.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('.gallery').rowGrid({
                itemSelector: '.photo',
                resize: true,
                minMargin: 5,
                maxMargin: 5
            });
        });
    </script>
	<script src="{{ url_for('static', filename='js/dialog.js') }}"></script>
    <script>
		$(document).on('ready dialog-content-loaded', function(e){
			var $dialog = $(e.target);
			$dialog.find('.pager a').data('popup', 'modal');
			$dialog.find('.pager a').on('click', function(e){
				loadDialog(e, this);
				$dialog.modal('hide');
			});
		});
    </script>
{% endblock %}

photocee/templates/contests/poll_option.html
{% extends 'dialog.html' %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/contests.ss') }}">
{% endblock %}

{% block modal_class%}{{ super() }} modal-lg photo-modal{% endblock %}

{% block modal_content %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Photo {{ current_index+1 }}</h4>
    </div>
    <img src="{{ url_for('contests.poll_options_photo', poll_option_id=poll_option.id, width=1800) }}" alt="Photo">
    {% if poll_option.description %}
        <div class="modal-body description">
            <h4>Description</h4>
            <p>{{ poll_option.description }}</p>
        </div>
    {% endif %}
    <div class="modal-footer">
        <ul class="pager">
            {% if previous_id %}
                <li class="previous"><a href="{{url_for('contests.poll_options_view', poll_option_id=previous_id)}}">Previous</a></li>
            {% endif %}
            {% if next_id %}
                <li class="next"><a href="{{url_for('contests.poll_options_view', poll_option_id=next_id)}}">Next</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

photocee/templates/contests/poll_option_delete_form.html
{% extends 'dialog.html' %}

{% block modal_title %}{{ meta.name }}{% endblock %}

{% block modal_content %}
<form method="POST" action="{{ url_inject_args(request.url, dict(next=meta.next)) if meta.next else request.url}}" role="form" class="form">
    <div style="display:none;"><input id="csrf_token" name="csrf_token" value="{{ csrf_token() }}" type="hidden"></div>
    {{ super() }}
</form>
{% endblock %}

{% block modal_body %}
    Are you sure you want to delete this photo?
{% endblock %}

{% block content_controls %}
    {% if meta.cancel_url %}<a href="{{ meta.cancel_url }}" class="btn btn-default" data-dismiss="modal">Cancel</a>{% endif %}
    <button type="submit" class="btn btn-danger">Delete</button>
{% endblock %}