photocee/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_wtf.csrf import CsrfProtect
import flask_uploads
from flask_coverapi import CoverSessionManager

# Init app
app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)
migrate = Migrate(app, db)

session_manager = CoverSessionManager(app.config['COVER_APP'], app.config['COVER_SECRET'], flask_app=app)

photos_uploadset = flask_uploads.UploadSet('photos', flask_uploads.IMAGES)
flask_uploads.configure_uploads(app, (photos_uploadset,))

CsrfProtect(app)

from .planner import planner, models
from .wall_of_fame import wall_of_fame, models
from .contests import contests, models

app.register_blueprint(planner)
app.register_blueprint(wall_of_fame)
app.register_blueprint(contests)

from . import views, utils

photocee/contests/__init__.py
from flask import Blueprint

contests = Blueprint('contests', __name__, url_prefix='/contests')

from . import views, utils

photocee/contests/views.py
from PIL import Image

from flask import render_template, url_for, redirect, request
from flask_coverapi import admin_required, login_required, current_user

from photocee import db, photos_uploadset
from photocee.caching import serve_cached_image

from . import contests
from .models import Poll, PollOption, PollVote, PollVoteRegistered
from .forms import PollForm, PollOptionForm, PollVoteForm
from .utils import randomize_for_user, get_poll_option_index, get_previous_poll_option_id, get_next_poll_option_id


@contests.route('/', methods=['GET'])
def main():
    view = request.args.get('view', 'default')

    if not current_user.is_anonymous:
        cover_id = current_user.get_id()
    else:
        cover_id = 0
    votes = PollVoteRegistered.query.filter_by(cover_id=cover_id).all()

    if view == 'archived':
        polls = Poll.query.order_by(Poll.deadline.desc()).all()
    else:
        polls = Poll.query.filter_by(archived=False).order_by(Poll.deadline.desc()).all()

    return render_template('contests/main.html', view=view, polls=polls, votes=[v.poll_id for v in votes])


@contests.route('/polls/add', methods=['GET','POST'])
@admin_required
def polls_add():
    form = PollForm()
    if form.validate_on_submit():
        poll = Poll(
            name=form.name.data,
            description=form.description.data,
            deadline=form.deadline.data,
            archived=form.archived.data,
        )
        db.session.add(poll)
        db.session.commit()
        return redirect(url_for('contests.polls_view', poll_id=poll.id))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Add poll',
        'cancel_url': url_for('contests.main')
    })


@contests.route('/polls/<int:poll_id>', methods=['GET'])
@admin_required
def polls_view(poll_id):
    poll = Poll.query.get_or_404(poll_id)
    results = []
    for idx, option in enumerate(poll.options):
        votes = option.votes.all()
        results.append({
            'option_id': option.id,
            'display': 'Photo {}'.format(idx+1),
            'votes': len(votes)
            })
    number_votes = sum([r['votes'] for r in results])
    form = PollOptionForm()
    return render_template('contests/poll.html', 
        poll=poll, 
        results=results, 
        number_votes=number_votes,
        form=form
        )


@contests.route('/polls/<int:poll_id>/vote', methods=['GET', 'POST'])
@login_required
def polls_vote(poll_id):
    poll = Poll.query.get_or_404(poll_id)
    form = PollVoteForm()
    form.choice.choices = [(o.id, "Photo {}".format(idx+1)) for idx, o in enumerate(randomize_for_user(poll.options))]
    if form.validate_on_submit():
        vote = PollVote(
            position=1,
            poll_option_id=form.choice.data,
            )
        registered = PollVoteRegistered(
            cover_id=current_user.get_id(),
            poll_id=poll.id
            )
        db.session.add(vote)
        db.session.add(registered)
        db.session.commit()
        return redirect(url_for('contests.main'))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Choose your favourite photo!',
        'cancel_url': url_for('contests.main')
    })


@contests.route('/polls/<int:poll_id>/edit', methods=['GET','POST'])
@admin_required
def polls_edit(poll_id):
    poll = Poll.query.get_or_404(poll_id)
    form = PollForm(request.form, poll)
    if form.validate_on_submit():
        form.populate_obj(poll)
        db.session.commit()
        return redirect(url_for('contests.polls_view', poll_id=poll.id))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Edit poll',
        'cancel_url': url_for('contests.polls_view', poll_id=poll.id)
    })


@contests.route('/polls/<int:poll_id>/options/add', methods=['GET', 'POST'])
@admin_required
def poll_options_add(poll_id):
    poll = Poll.query.get_or_404(poll_id)
    form = PollOptionForm()
    if form.validate_on_submit():
        filename = photos_uploadset.save(form.photo.data)
        with Image.open(photos_uploadset.path(filename)) as im:
            width, height = im.size
        poll_option = PollOption(
            description=form.description.data,
            photo_name=filename,
            width=width,
            height=height,
            poll=poll
        )
        db.session.add(poll_option)
        db.session.commit()
        return redirect(url_for('contests.polls_view', poll_id=poll.id))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Add option to {}'.format(poll.name),
        'cancel_url': url_for('contests.polls_view', poll_id=poll.id),
        'form_kwargs': {'upload': True}
    })


@contests.route('/polls/options/<int:poll_option_id>', methods=['GET'])
def poll_options_view(poll_option_id):
    poll_option = PollOption.query.get_or_404(poll_option_id)
    return render_template(
        'contests/poll_option.html',
        poll_option=poll_option,
        current_index=get_poll_option_index(poll_option.poll.options, poll_option),
        previous_id=get_previous_poll_option_id(poll_option.poll.options, poll_option),
        next_id=get_next_poll_option_id(poll_option.poll.options, poll_option)
    )


@contests.route('/polls/options/<int:poll_option_id>/photo', methods=['GET'])
def poll_options_photo(poll_option_id):
    width = request.args.get('width', None)
    height = request.args.get('height', None)
    if width and width.strip():
        width = int(float(width))
    if height and height.strip():
        height = int(float(height))
    poll_option = PollOption.query.get_or_404(poll_option_id)
    return serve_cached_image('photos', poll_option.photo_name, width, height)


@contests.route('/polls/options/<int:poll_option_id>/delete', methods=['GET', 'POST'])
@admin_required
def poll_options_delete(poll_option_id):
    poll_option = PollOption.query.get_or_404(poll_option_id)
    if request.method == 'POST':
        db.session.delete(poll_option)
        db.session.commit()
        return redirect(url_for('contests.polls_view', poll_id=poll_option.poll_id))
    return render_template('contests/poll_option_delete_form.html', poll_option=poll_option, meta={
        'name': 'Delete photo',
        'cancel_url': url_for('contests.polls_view', poll_id=poll_option.poll_id)
    })

photocee/planner/__init__.py
from flask import Blueprint

planner = Blueprint('planner', __name__, url_prefix='/planner')

from . import views

photocee/planner/views.py
from __future__ import division

from flask import request, render_template, redirect, url_for, abort, flash, get_flashed_messages, current_app
from flask_coverapi import admin_required, current_user, CoverSession

from sqlalchemy.orm import Load
from sqlalchemy.sql import func

from urlparse import urlparse, urljoin
from datetime import datetime

import sqlalchemy_utils
import json

from photocee import db
from photocee.utils import redirect_or_next, url_for_or_next

from . import planner
from .models import Activity, Photographer, PHOTOGRAPHER_STATUS_OPTIONS
from .forms import ActivityForm, PhotographerForm


def _update_activities():
    activities = current_app.cover_session_manager.request_json({
            'method': 'agenda',
            'session_id': current_user.session_id
        })
    for activity in activities:
        if activity['replacement_for'] is not None:
            # Unapproved activity, skip.
            continue
        saved_activity = Activity.query.filter_by(cover_id=activity['id']).first()
        if not saved_activity:
            saved_activity = Activity(cover_id=int(activity['id']))
            db.session.add(saved_activity)
        saved_activity.name = activity['kop']
        saved_activity.date = datetime.strptime(activity['van'].split('+', 1)[0], '%Y-%m-%d %H:%M:%S')
        saved_activity.location = activity['locatie']
    db.session.commit()


def _apply_filters(query):
    filters = {}

    if request.args.get('archived') == 'None':
        archived = None
    else:
        archived = request.args.get('archived') == 'True'

    if archived is not None:
        query = query.filter(Activity.archived == archived)

    if request.args.get('published') and request.args.get('published') != 'None':
        filters['published'] = request.args.get('published') == 'True'
        query = query.filter(Activity.published == filters['published'])

    if request.args.get('status') or request.args.get('photographers'):
        photographers_query = db.session.query(Photographer.activity_id)

        if request.args.get('photographers'):
            filters['photographers'] = request.args.get('photographers')
            photographers = request.args.get('photographers').split(',')
            photographers_query = photographers_query.filter(Photographer.cover_id.in_(photographers))

        if request.args.get('status'):
            filters['status'] = request.args.getlist('status')
            photographers_query = photographers_query.filter(Photographer.status.in_(filters['status']))

        query = query.filter(Activity.id.in_(photographers_query.subquery()))

    if filters or request.args.get('archived'):
        filters['archived'] = archived

    return query, filters


@planner.route('/', methods=['GET'])
@admin_required
def main():
    _update_activities()
    
    my_activities_subq = Photographer.query.filter_by(cover_id=current_user.get_id()).subquery()
    activities_query = db.session.query(Activity, my_activities_subq.c.status.label('my_status')).outerjoin(my_activities_subq, Activity.id==my_activities_subq.c.activity_id)
    
    backlog = db.session.query(func.count(Activity.id))\
                .outerjoin(my_activities_subq, Activity.id==my_activities_subq.c.activity_id)\
                .filter(my_activities_subq.c.cover_id == current_user.get_id())\
                .filter(my_activities_subq.c.status == u'0')\
                .filter(Activity.archived==False)\
                .filter(Activity.date < datetime.now())\
                .scalar()

    #filters
    activities_query, filters = _apply_filters(activities_query)

    activities = activities_query.order_by(Activity.date.desc()).all()

    return render_template('planner/planner.html', 
                           activities=activities, 
                           status_options=dict(PHOTOGRAPHER_STATUS_OPTIONS),
                           status_options_json=json.dumps(dict(PHOTOGRAPHER_STATUS_OPTIONS)), 
                           filters=filters,
                           backlog=backlog)


@planner.route('/status', methods=['POST'])
@admin_required
def update_status():
    photographer = current_user
    for key, value in request.form.iteritems():
        fieldname = key.split('-', 1)
        if not fieldname[0] == 'status':
            continue

        activity_id = fieldname[-1]
        activity = Activity.query.get(activity_id)
        if activity:
            add_or_update_photographer(photographer, activity, value)
    db.session.commit()
    return redirect_or_next(url_for('planner.main'))


def add_or_update_photographer(photographer, activity, status):
    saved_photographer = Photographer.query.filter_by(activity_id=activity.id).filter_by(cover_id=photographer.get_id()).first()
    if not saved_photographer:
        saved_photographer = Photographer(activity_id=activity.id, cover_id=photographer.get_id(), name=photographer.full_name, status=status)
        db.session.add(saved_photographer)
    else:
        saved_photographer.status = status
    auto_archive(activity)


def auto_archive(activity):
    if not activity.published:
        return
    db.session.commit()
    if not Photographer.query.filter_by(activity_id=activity.id).filter(Photographer.status.in_([u'0', u'2', u'3'])).first():
        activity.archived = True
    else: 
        activity.archived = False


@planner.route('/activity/<int:activity_id>/status/add', methods=['GET', 'POST'])
@admin_required
def add_status_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    form = PhotographerForm()
    if form.validate_on_submit():
        response = current_app.cover_session_manager.request_json({
            'method': 'get_member',
            'session_id': current_user.session_id,
            'member_id': form.photographer_cover_id.data
        })
        if 'result' in response:
            photographer = CoverSession(current_user.api, current_user.session_id, response['result'])
        else:
            return "Invalid Cover Member ID", 400
        add_or_update_photographer(photographer, activity, form.status.data)
        db.session.commit()
        return redirect_or_next(url_for('planner.main'))
    return render_template('planner/photographer_form.html', form=form, activity=activity, meta={
        'name': 'Add photographer',
        'cancel_url': url_for_or_next('planner.main')
    })


@planner.route('/<int:activity_id>/archive', methods=['GET'])
@admin_required
def archive_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    activity.archived = request.args.get('archive') != 'False'
    db.session.commit()
    return redirect_or_next(url_for('planner.main'))


@planner.route('/<int:activity_id>/publish', methods=['GET'])
@admin_required
def publish_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    activity.published = request.args.get('publish') != 'False'
    auto_archive(activity)
    db.session.commit()
    return redirect_or_next(url_for('planner.main'))


@planner.route('/activity/add', methods=['GET', 'POST'])
@admin_required
def add_activity():
    """ Try to create a new activity. """
    form = ActivityForm()
    if form.validate_on_submit():
        activity = Activity(
            name=form.name.data, description=form.description.data, location=form.location.data, date=form.date.data, cover_id=form.cover_id.data)
        db.session.add(activity)
        db.session.commit()
        return redirect(url_for('planner.main'))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Add activity',
        'cancel_url': url_for('planner.main')
    })



@planner.route('/activity/<int:activity_id>', methods=['GET', 'POST'])
@admin_required
def edit_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    form = ActivityForm(request.form, activity)
    if form.validate_on_submit():
        form.populate_obj(activity)
        db.session.commit()
        return redirect_or_next(url_for('planner.main'))
    return render_template('form_dialog.html', form=form, meta={
        'name': 'Edit activity',
        'cancel_url': url_for_or_next('planner.main')
    })

photocee/views.py
import requests

from flask import render_template, request, jsonify
from flask_coverapi import admin_required, current_user, CoverSession

from . import app

@app.route('/', methods=['GET'])
def view_home():
    return render_template('index.html')


@app.route('/almanakproxy', methods=['GET'])
@admin_required
def almanakproxy():
    cover_cookie_name = app.config.get('COVER_COOKIE_NAME', 'cover_session_id')
    almanak_url = app.config.get('COVER_ALMANAK_URL', 'https://www.svcover.nl/almanak.php')
    params = dict(request.args)
    if request.cookies.get(cover_cookie_name):
        params['session_id'] = request.cookies.get(cover_cookie_name)
    response = requests.get(almanak_url, params=params, headers={'accept': 'application/json, text/javascript'})
    response.raise_for_status()
    return response.text


@app.route('/almanakreverse', methods=['GET'])
@admin_required
def almanakreverse():
    query = request.args.get('search', '').split(',')
    def generate(data):
        for member_id in data:
            print member_id
            response = app.cover_session_manager.request_json({
                'method': 'get_member',
                'session_id': current_user.session_id,
                'member_id': member_id
            })

            if not 'result' in response:
                continue

            photographer = CoverSession(current_user.api, current_user.session_id, response['result'])
            yield {
                'id': photographer.get_id(),
                'name': photographer.full_name,
                'first_name': photographer.user['voornaam']
            }
    return jsonify(list(generate(query)))

photocee/wall_of_fame/__init__.py
from flask import Blueprint

wall_of_fame = Blueprint('wall_of_fame', __name__, url_prefix='/wall-of-fame')

from . import views

photocee/templates/base.html
{% macro render_errors(field, class='alert alert-danger') -%}
    {% if field.errors %}
        {% for error in field.errors %}
        <div class="{{class}}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Oh dear!</strong> {{ error }}
        </div>
        {% endfor %}
    {% endif %}
{%- endmacro %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobileoptimized" content="0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
    <title>{% block title %}PhotoCee{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    {% endblock %}
</head>
<body id="{% block page_id %}{% endblock %}">
    <nav class="offcanvas">
        <ul>
            <li class="toggle-offcanvas"><a href="#navbar-main" data-toggle="offcanvas" title="Expand nav"><i class="fa fa-times"></i></a></li>
            <li class="brand">
                <a href="/">
                    <svg class="logo" width="100" height="100" version="1.1" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd" viewBox="0 0 10000 10000"><g><path d="M940 2414l2053 0 265 -359 3484 0 265 359 2053 0 0 5531 -8120 0 0 -5531zm4660 1973c189,0 342,154 342,342 0,189 -153,342 -342,342 -189,0 -342,-153 -342,-342 0,-188 153,-342 342,-342zm-600 -363c671,0 1215,544 1215,1215 0,671 -544,1216 -1215,1216 -671,0 -1215,-545 -1215,-1216 0,-671 544,-1215 1215,-1215zm0 -268c819,0 1483,664 1483,1483 0,819 -664,1483 -1483,1483 -819,0 -1483,-664 -1483,-1483 0,-819 664,-1483 1483,-1483zm1455 -561c175,125 334,272 472,438l1545 0 0 -438 -2017 0zm672 713c60,96 114,197 161,301l1184 0 0 -301 -1345 0zm266 577c31,97 56,198 75,301l1004 0 0 -301 -1079 0zm110 576c4,59 6,118 6,178 0,41 -1,82 -3,123l966 0 0 -301 -969 0zm-26 576c-16,103 -39,203 -67,301l1062 0 0 -301 -995 0zm-164 577c-44,104 -95,204 -152,301l1311 0 0 -301 -1159 0zm-341 576c-109,139 -233,266 -368,378l1868 0 0 -378 -1500 0zm-3576 378c-135,-112 -259,-239 -368,-378l-1499 0 0 378 1867 0zm-557 -653c-57,-97 -108,-197 -152,-301l-1158 0 0 301 1310 0zm-249 -577c-28,-98 -51,-198 -67,-301l-994 0 0 301 1061 0zm-96 -576c-2,-41 -3,-82 -3,-123 0,-60 2,-119 6,-178l-968 0 0 301 965 0zm38 -576c19,-103 44,-204 75,-301l-1078 0 0 301 1003 0zm180 -577c47,-104 101,-205 161,-301l-1344 0 0 301 1183 0zm361 -576c138,-166 297,-313 472,-438l-2016 0 0 438 1544 0z"/></g></svg>
                    <span class="caption">PhotoCee</span>
                </a>
            </li>
            <li class="{{ current_page(prefixes=['contests']) }}">
                <a href="{{ url_for('contests.main') }}">
                    <svg width="313px" height="307px" version="1.1" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd" viewBox="0 0 5154 5064"><g><path d="M3108 2577l833 -833 422 422 469 -16 -649 -649 -134 -134 754 -754c93,13 190,-15 261,-86 121,-121 121,-316 0,-437 -121,-121 -316,-121 -437,0 -71,71 -99,168 -86,261l-754 754 -134 -134 -649 -649 -16 469 422 422 -833 833 -833 -833 422 -422 -16 -469 -649 649 -134 134 -754 -754c13,-93 -15,-190 -86,-261 -121,-121 -316,-121 -437,0 -121,121 -121,316 0,437 71,71 168,99 261,86l754 754 -134 134 -649 649 469 16 422 -422 833 833 -1917 1917 -39 570 2204 -2239 244 -247 39 -40 243 -247 827 -840 57 57 -840 827 -248 244 -39 39 -248 244 -2239 2204 570 -39 1917 -1917 1916 1917 570 39 -2239 -2204 35 -35 2204 2239 -40 -570 -1917 -1916zm-818 -244l-840 -827 57 -57 827 840 -43 43z"/></g></svg>
                    <span class="caption">Photo Contest</span>
                </a>
            </li>
            {#<li>
                <a href="#">
                    <svg x="0px" y="0px" width="100px" height="100px" viewBox="0 0 100 100" enable-background="new 0 0 100 100"><g><path d="M92.48,19.309c-1.084,0-1.962,0.878-1.962,1.961v49.49c-13.096-3.783-22.897-1.934-28.943,0.392   c-4.589,1.765-7.724,4.032-9.403,5.454c-6.852-5.954-16.214-8.753-27.219-8.107c-5.552,0.326-10.259,1.441-13.03,2.239V21.27   c0-1.083-0.878-1.961-1.961-1.961C8.878,19.309,8,20.187,8,21.27v52.156c0,0.645,0.316,1.246,0.845,1.612   c0.529,0.366,1.204,0.449,1.806,0.225c0.251-0.094,25.248-9.228,40.15,5.415c0.367,0.36,0.862,0.56,1.377,0.56   c0.016,0,0.032-0.001,0.049-0.001c0.53-0.013,1.035-0.243,1.396-0.632c0.032-0.035,3.276-3.501,9.566-5.869   c8.325-3.138,18.237-2.947,28.668,0.55c0.598,0.201,1.256,0.102,1.769-0.267c0.513-0.369,0.816-0.961,0.816-1.593V21.27   C94.441,20.187,93.563,19.309,92.48,19.309z"/><path d="M16.416,68.044c3.861-0.968,11.521-2.456,18.235-1.12c7.547,1.505,13.854,5.463,15.947,6.89   c0.42,0.229,0.568,0.309,0.739,0.305c0.261,0.004,0.318-0.075,0.738-0.305c2.092-1.427,8.398-5.385,15.946-6.89   c6.714-1.336,14.375,0.152,18.235,1.12c1.594,0.408,2.508-0.672,2.508-1.771V20.125c0-1.579-0.827-2.529-2.415-3.128   c-3.821-0.971-11.521-2.494-18.268-1.149c-9.3,1.851-16.745,7.418-16.745,7.418s-7.447-5.568-16.747-7.418   c-6.746-1.345-14.446,0.178-18.268,1.149c-1.588,0.599-2.415,1.549-2.415,3.128v46.148C13.908,67.372,14.821,68.452,16.416,68.044z   "/></g></svg>
                    <span class="caption">Photo Gallery</span>
                </a>
            </li>#}
            <li class="{{ current_page(prefixes=['wall-of-fame']) }}"><a href="{{ url_for('wall_of_fame.main') }}"><i class="fa fa-trophy"></i> <span class="caption">Wall of Fame</span></a></li>
            <li><a href="https://www.youtube.com/user/fotocie" target="_blank"><i class="fa fa-youtube-play"></i> <span class="caption">Youtube</span></a></li>
            <li><a href="https://www.facebook.com/fotocie" target="_blank"><i class="fa fa-facebook-square"></i> <span class="caption">Facebook</span></a></li>
        {% if current_cover_user.is_admin %}
            <li class="{{ current_page(prefixes=['planner']) }}"><a href="{{url_for('planner.main')}}"><i class="fa fa-calendar"></i> <span class="caption">Planner</span></a></li>
        {% endif %}
        </ul>
        <ul class="bottom-controls">
        {% if current_cover_user.is_authenticated %}
            <li class="user">
                <a href="{{ logout_url()}}">
                    <span class="avatar">
                        <img src="https://www.svcover.nl/foto.php?lid_id={{current_cover_user.get_id()}}&amp;format=square&amp;width=100">
                    </span>
                    <span class="caption">Logout {{current_cover_user.name}}</span>
                </a>
            </li>
        {% else %}
            <li><a href="{{ login_url() }}"><i class="fa fa-user"></i> <span class="caption">Login</span></a></li>
        {% endif %}
            <li>
                <a href="https://www.svcover.nl/" target="_blank">
                    <svg width="120px" height="120px" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd" viewBox="0 0 12000 12000"><g><path d="M10444 1540l-237 2717 -551 0 0 -1408c-632,-748 -1545,-1137 -2638,-1137 -2139,0 -3592,1489 -3592,4252 0,2764 1453,4253 3592,4253 940,0 1926,-166 2890,-684l383 656c-777,620 -2245,987 -3273,987 -3427,0 -5756,-1799 -5756,-5139 0,-3340 2329,-5140 5756,-5140 1344,0 2340,244 3426,643z"/></g></svg>
                    <span class="caption">Study Association Cover</span>
                </a>
            </li>
        </ul>
    </nav>
    <div class="page-wrap row-offcanvas row-offcanvas-left">
        {% block page %}
            <header>
                {% block header%}
                <a href="#navbar-main" class="toggle-offcanvas" data-toggle="offcanvas" title="Expand nav"><i class="fa fa-bars"></i></a>
                <h1>{% block page_title %}{% endblock %}</h1>
                {% endblock %}
            </header>
            <div class="content">
            {% block content %}{% endblock %}
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info alert-dismissible alert-flash" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            </div>
        {% endblock %}
    </div>
{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/offcanvas.js') }}"></script>
{% endblock %}
</body>
</html>

photocee/templates/form.html
{% extends 'base.html' %}

{% from 'form_macros.html' import render_form %}

{%block page_class %}container-narrow{% endblock %}

{% block page_title %}{{ meta.name }}{% endblock %}

{% block content %}
	{% if meta.form_kwargs is defined %}
		{{ render_form(form, action_text='Submit', **meta.form_kwargs ) }}
	{% else %}
		{{ render_form(form, action_text='Submit') }}
    {% endif %}
{% endblock %}

photocee/templates/index.html
{% extends "base.html" %}

{% block page_title %}PhotoCee Cover{% endblock %}

{% block content %}
<section>
    <p>
        The <a href="https://www.svcover.nl/commissies.php?commissie=photocee">PhotoCee</a> is the committee that takes pictures and sometimes video's during the activities of Cover. Sometimes we even organise a Photo Workshop, a Photo Chain Letter, a Photo Quiz or a Photo Contest.
    </p>
    <p>
    	The winners of the contest are exhibited on the <a href="{{ url_for('wall_of_fame.main')}}">Wall of Fame</a>. We also invite we invite you to take a look at our <a href="https://www.youtube.com/user/fotocie">Youtube channel</a> or <a href="https://www.facebook.com/fotocie">Facebook page</a>, where we notify you when we publish new photos of events!
    </p>
</section>
{% endblock %}